name: Metrics

on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

  leetcode:
  uses: lowlighter/metrics@latest
  with:
    filename: leetcode.svg
    token: NOT_NEEDED
    base: ""
    plugin_leetcode: yes
    plugin_leetcode_sections: solved, skills, recent
